#pragma once

#include <cstddef>
#include <string>
#include <vector>

namespace Core::VersionSystem {

/// Represents a single file captured in a version snapshot.
struct FileEntry {
    /// Repo-relative or absolute path to the file.
    std::string Path;

    /// FNV-1a hash of the file content encoded as a lowercase hex string.
    std::string Hash;

    /// File size in bytes at the time the snapshot was taken.
    std::size_t Size{0};
};

/// An immutable record of the state of a directory tree at a point in time.
///
/// VersionSnapshot is produced by VersionSystem::CreateSnapshot() and can be
/// stored in the version history, saved to disk, and compared to detect
/// changes between snapshots.
struct VersionSnapshot {
    /// Unique identifier (pseudo-UUID generated by VersionSystem).
    std::string ID;

    /// ISO 8601 UTC timestamp of when the snapshot was taken.
    std::string Timestamp;

    /// Human-readable description of what this snapshot represents.
    std::string Description;

    /// All files found under the scanned directory at snapshot time.
    std::vector<FileEntry> Files;
};

} // namespace Core::VersionSystem
