#include "Tools/Scaffolding/CodeScaffolder.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;
namespace Tools {

// ─────────────────────────────────────────────────────────────────────────────
// Default templates (inline)
// ─────────────────────────────────────────────────────────────────────────────

static const char* kHeaderTemplate = R"(#pragma once
// ${CLASS_NAME} — ${DESCRIPTION}

#include <string>

namespace ${NAMESPACE} {

class ${CLASS_NAME} {
public:
    ${CLASS_NAME}();
    ~${CLASS_NAME}();

    void Init();
    void Shutdown();
    void Update(float dt);

private:
};

} // namespace ${NAMESPACE}
)";

static const char* kSourceTemplate = R"(#include "${INCLUDE_PATH}"

namespace ${NAMESPACE} {

${CLASS_NAME}::${CLASS_NAME}()  {}
${CLASS_NAME}::~${CLASS_NAME}() {}
void ${CLASS_NAME}::Init()             {}
void ${CLASS_NAME}::Shutdown()         {}
void ${CLASS_NAME}::Update(float /*dt*/) {}

} // namespace ${NAMESPACE}
)";

static const char* kCMakeTemplate = R"(add_library(${LIBRARY_NAME} STATIC
    ${CLASS_NAME}/${CLASS_NAME}.cpp
)
target_include_directories(${LIBRARY_NAME} PUBLIC ${CMAKE_SOURCE_DIR})
target_compile_features(${LIBRARY_NAME} PUBLIC cxx_std_20)
)";

static const char* kAgentHeaderTemplate = R"(#pragma once
// ${CLASS_NAME} — AI Agent (generated by CodeScaffolder)

#include "AI/Orchestrator/Orchestrator.h"
#include <string>

namespace AI {

class ${CLASS_NAME} {
public:
    ${CLASS_NAME}();

    /// Register this agent with an Orchestrator.
    void Register(AI::Orchestrator& orchestrator);

    /// Execute a job assigned to this agent.
    bool Execute(AI::OrchestratorJob& job);

private:
    std::string m_name = "${CLASS_NAME}";
};

} // namespace AI
)";

// ─────────────────────────────────────────────────────────────────────────────
// TemplateEngine
// ─────────────────────────────────────────────────────────────────────────────

TemplateEngine::TemplateEngine(const std::string& root)
    : m_root(root)
{}

std::string TemplateEngine::Load(const std::string& name) const
{
    // Check inline first
    auto it = m_inline.find(name);
    if (it != m_inline.end()) return it->second;

    // Try file system
    if (!m_root.empty()) {
        std::ifstream f(m_root + "/" + name);
        if (f) {
            return std::string(std::istreambuf_iterator<char>(f),
                               std::istreambuf_iterator<char>());
        }
    }
    return {};
}

/* static */
std::string TemplateEngine::Render(
    const std::string& tmpl,
    const std::unordered_map<std::string,std::string>& vars)
{
    std::string result = tmpl;
    for (const auto& [key, val] : vars) {
        std::string token = "${" + key + "}";
        size_t pos = 0;
        while ((pos = result.find(token, pos)) != std::string::npos) {
            result.replace(pos, token.size(), val);
            pos += val.size();
        }
    }
    return result;
}

void TemplateEngine::RegisterInline(const std::string& name,
                                     const std::string& content)
{
    m_inline[name] = content;
}

// ─────────────────────────────────────────────────────────────────────────────
// CodeScaffolder
// ─────────────────────────────────────────────────────────────────────────────

CodeScaffolder::CodeScaffolder(CodeScaffolderConfig cfg)
    : m_cfg(std::move(cfg))
{
    if (m_cfg.templateRoot.empty() && !m_cfg.repoRoot.empty())
        m_cfg.templateRoot = m_cfg.repoRoot + "/Scripts/Templates";
    m_templates = TemplateEngine(m_cfg.templateRoot);
    RegisterDefaultTemplates();
}

void CodeScaffolder::RegisterDefaultTemplates()
{
    m_templates.RegisterInline("class_header.h", kHeaderTemplate);
    m_templates.RegisterInline("class_source.cpp", kSourceTemplate);
    m_templates.RegisterInline("cmake.txt",      kCMakeTemplate);
    m_templates.RegisterInline("agent_header.h", kAgentHeaderTemplate);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

std::string CodeScaffolder::SandboxPath(const std::string& rel) const
{
    return m_cfg.sandboxRoot + "/" + rel;
}

bool CodeScaffolder::WriteFile(const std::string& path,
                                const std::string& content,
                                ScaffoldResult& result) const
{
    if (!m_cfg.overwrite && fs::exists(path)) {
        result.filesSkipped.push_back(path);
        return true;
    }
    if (m_cfg.confirmFn && !m_cfg.confirmFn(path)) {
        result.filesSkipped.push_back(path);
        return true;
    }
    if (m_cfg.dryRun) {
        result.filesCreated.push_back(path + " [dry-run]");
        return true;
    }
    try {
        fs::create_directories(fs::path(path).parent_path());
        std::ofstream f(path);
        if (!f) {
            result.errors.push_back("Cannot write: " + path);
            return false;
        }
        f << content;
        result.filesCreated.push_back(path);
        return true;
    } catch (const std::exception& e) {
        result.errors.push_back(std::string(e.what()));
        return false;
    }
}

// ── ScaffoldClass ─────────────────────────────────────────────────────────────

ScaffoldResult CodeScaffolder::ScaffoldClass(const std::string& className,
                                              const std::string& ns,
                                              const std::string& rootDir)
{
    ModuleBlueprint bp;
    bp.name      = className;
    bp.ns        = ns;
    bp.rootDir   = rootDir;
    bp.description = "Generated by CodeScaffolder";

    std::string nsSlash = ns;
    for (auto& c : nsSlash) if (c == ':') c = '/';

    bp.components.push_back({
        ComponentKind::CppHeader,
        className + "/" + className + ".h",
        "class_header.h",
        {{"CLASS_NAME", className}, {"NAMESPACE", ns},
         {"DESCRIPTION", bp.description}}
    });
    bp.components.push_back({
        ComponentKind::CppSource,
        className + "/" + className + ".cpp",
        "class_source.cpp",
        {{"CLASS_NAME", className}, {"NAMESPACE", ns},
         {"INCLUDE_PATH", rootDir + "/" + className + "/" + className + ".h"}}
    });
    return ScaffoldModule(bp);
}

ScaffoldResult CodeScaffolder::ScaffoldAgent(const std::string& agentName)
{
    ScaffoldResult result;
    result.sandboxPath = SandboxPath("Agents/" + agentName);

    std::unordered_map<std::string,std::string> vars;
    vars["CLASS_NAME"] = agentName;

    auto hTmpl = m_templates.Load("agent_header.h");
    if (hTmpl.empty()) { result.passed = false; result.errors.push_back("Template not found"); return result; }

    std::string hContent = TemplateEngine::Render(hTmpl, vars);
    WriteFile(result.sandboxPath + "/" + agentName + ".h", hContent, result);
    result.passed = result.errors.empty();
    return result;
}

ScaffoldResult CodeScaffolder::ScaffoldModule(const ModuleBlueprint& bp)
{
    ScaffoldResult result;
    result.sandboxPath = SandboxPath(bp.rootDir);

    for (const auto& comp : bp.components) {
        // Merge blueprint vars + component vars
        auto vars = comp.vars;
        vars["CLASS_NAME"]   = bp.name;
        vars["NAMESPACE"]    = bp.ns;
        vars["LIBRARY_NAME"] = bp.libraryName.empty() ? bp.name + "Lib" : bp.libraryName;
        vars["DESCRIPTION"]  = bp.description;

        auto tmpl = m_templates.Load(comp.templateName);
        if (tmpl.empty()) tmpl = "// " + comp.relativePath + " — generated\n";

        std::string content = TemplateEngine::Render(tmpl, vars);
        std::string path    = result.sandboxPath + "/" + comp.relativePath;
        WriteFile(path, content, result);
    }

    result.passed = result.errors.empty();
    return result;
}

// ── Finalise / Discard ────────────────────────────────────────────────────────

bool CodeScaffolder::Finalise(const ScaffoldResult& result)
{
    if (result.sandboxPath.empty()) return false;
    if (m_cfg.dryRun) return true;
    try {
        // Move sandbox subtree → real dest
        // Replace sandbox prefix with repoRoot
        for (const auto& f : result.filesCreated) {
            auto sf = f;
            if (sf.rfind(m_cfg.sandboxRoot, 0) == 0)
                sf = sf.substr(m_cfg.sandboxRoot.size() + 1);
            std::string dst = m_cfg.repoRoot + "/" + sf;
            fs::create_directories(fs::path(dst).parent_path());
            std::string src = f;
            if (src.find("[dry-run]") != std::string::npos) continue;
            if (fs::exists(src))
                fs::copy_file(src, dst,
                              fs::copy_options::overwrite_existing);
        }
        return true;
    } catch (...) {
        return false;
    }
}

void CodeScaffolder::Discard(const ScaffoldResult& result)
{
    if (!result.sandboxPath.empty())
        fs::remove_all(result.sandboxPath);
}

// ── Reporting ─────────────────────────────────────────────────────────────────

TemplateEngine& CodeScaffolder::GetTemplateEngine() { return m_templates; }

std::string CodeScaffolder::BuildReport(const ScaffoldResult& result) const
{
    std::ostringstream oss;
    oss << "# Scaffold Report\n\n"
        << "**Result:** " << (result.passed ? "✅" : "❌") << "\n"
        << "**Files created:** " << result.filesCreated.size() << "\n"
        << "**Files skipped:** " << result.filesSkipped.size() << "\n"
        << "**Errors:** "        << result.errors.size() << "\n\n";

    if (!result.errors.empty()) {
        oss << "## Errors\n\n";
        for (const auto& e : result.errors) oss << "- " << e << "\n";
    }
    return oss.str();
}

} // namespace Tools
