#include "Builder/Export/ShipExporter.h"
#include <chrono>
#include <fstream>
#include <sstream>

namespace Builder {

static uint64_t NowMs() {
    using namespace std::chrono;
    return static_cast<uint64_t>(
        duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count());
}

struct ShipExporter::Impl {
    bool        loaded{false};
    std::string assemblyName;
    std::string assemblyJSON;
    uint32_t    partCount{0};

    std::function<void(const ExportResult&)>   onComplete;
    std::function<void(const std::string&)>    onError;

    ExportResult WriteFile(const std::string& path, const std::string& content) {
        ExportResult res;
        uint64_t t0 = NowMs();
        std::ofstream f(path);
        if (!f.is_open()) {
            res.errorMessage = "Cannot open: " + path;
            if (onError) onError(res.errorMessage);
            return res;
        }
        f << content;
        res.succeeded     = true;
        res.outputPath    = path;
        res.partCount     = partCount;
        res.fileSizeBytes = static_cast<uint64_t>(content.size());
        res.durationMs    = NowMs() - t0;
        if (onComplete) onComplete(res);
        return res;
    }
};

ShipExporter::ShipExporter() : m_impl(new Impl()) {}
ShipExporter::~ShipExporter() { delete m_impl; }

void ShipExporter::Init()     {}
void ShipExporter::Shutdown() {}

bool ShipExporter::LoadAssembly(const std::string& sessionPath) {
    std::ifstream f(sessionPath);
    if (!f.is_open()) return false;
    std::stringstream ss; ss << f.rdbuf();
    m_impl->assemblyJSON = ss.str();
    m_impl->assemblyName = sessionPath;
    m_impl->loaded       = true;
    // Count parts (rough: count "part_id" occurrences)
    m_impl->partCount    = 0;
    std::string token    = "\"part_id\"";
    size_t pos           = 0;
    while ((pos = m_impl->assemblyJSON.find(token, pos)) != std::string::npos) {
        ++m_impl->partCount; pos += token.size();
    }
    return true;
}

bool ShipExporter::LoadAssemblyFromJSON(const std::string& json) {
    m_impl->assemblyJSON = json;
    m_impl->assemblyName = "inline";
    m_impl->loaded       = true;
    return true;
}

bool        ShipExporter::IsAssemblyLoaded() const { return m_impl->loaded; }
std::string ShipExporter::AssemblyName()     const { return m_impl->assemblyName; }
uint32_t    ShipExporter::PartCount()        const { return m_impl->partCount; }

ExportResult ShipExporter::Export(const std::string& path, ExportFormat fmt,
                                  const ExportOptions& opts) {
    switch (fmt) {
        case ExportFormat::Blueprint: return ExportBlueprint(path, opts);
        case ExportFormat::OBJ:       return ExportOBJ(path, opts);
        case ExportFormat::PAK:       return ExportPAK(path, opts);
        case ExportFormat::GLB:       return ExportGLB(path, opts);
    }
    return {};
}

ExportResult ShipExporter::ExportBlueprint(const std::string& path,
                                           const ExportOptions& opts) {
    if (!m_impl->loaded) { ExportResult r; r.errorMessage="No assembly loaded"; return r; }
    std::ostringstream ss;
    ss << "{\n"
       << "  \"type\": \"blueprint\",\n"
       << "  \"name\": \"" << m_impl->assemblyName << "\",\n"
       << "  \"version\": \"" << opts.versionTag << "\",\n"
       << "  \"author\": \"" << opts.authorTag << "\",\n"
       << "  \"part_count\": " << m_impl->partCount << ",\n"
       << "  \"assembly\": " << m_impl->assemblyJSON << "\n"
       << "}\n";
    return m_impl->WriteFile(path, ss.str());
}

ExportResult ShipExporter::ExportOBJ(const std::string& path,
                                     const ExportOptions& /*opts*/) {
    if (!m_impl->loaded) { ExportResult r; r.errorMessage="No assembly loaded"; return r; }
    std::ostringstream ss;
    ss << "# OBJ export: " << m_impl->assemblyName << "\n";
    ss << "# Parts: " << m_impl->partCount << "\n";
    ss << "# Generated by ShipExporter\n\n";
    ss << "o Assembly\n";
    // Minimal placeholder geometry
    ss << "v 0.0 0.0 0.0\nv 1.0 0.0 0.0\nv 1.0 1.0 0.0\nv 0.0 1.0 0.0\n";
    ss << "f 1 2 3 4\n";
    return m_impl->WriteFile(path, ss.str());
}

ExportResult ShipExporter::ExportPAK(const std::string& path,
                                     const ExportOptions& /*opts*/) {
    if (!m_impl->loaded) { ExportResult r; r.errorMessage="No assembly loaded"; return r; }
    std::ostringstream ss;
    ss << "PAKV1 type=ship name=" << m_impl->assemblyName
       << " parts=" << m_impl->partCount << "\n"
       << m_impl->assemblyJSON;
    return m_impl->WriteFile(path, ss.str());
}

ExportResult ShipExporter::ExportGLB(const std::string& path,
                                     const ExportOptions& /*opts*/) {
    if (!m_impl->loaded) { ExportResult r; r.errorMessage="No assembly loaded"; return r; }
    // Minimal glTF 2.0 JSON stub (binary header + JSON chunk)
    std::ostringstream ss;
    ss << "{\"asset\":{\"version\":\"2.0\",\"generator\":\"ShipExporter\"},"
       << "\"scene\":0,\"scenes\":[{\"name\":\"" << m_impl->assemblyName << "\"}]}\n";
    return m_impl->WriteFile(path, ss.str());
}

std::vector<ExportResult>
ShipExporter::BatchExport(const std::string& /*sessionDir*/,
                          const std::string& outputDir,
                          ExportFormat format,
                          const ExportOptions& opts) {
    std::vector<ExportResult> results;
    // Stub: exports the currently loaded assembly if any
    if (!m_impl->loaded) return results;
    std::string ext = (format == ExportFormat::OBJ) ? ".obj"
                    : (format == ExportFormat::GLB) ? ".glb"
                    : (format == ExportFormat::PAK) ? ".pak" : ".json";
    results.push_back(Export(outputDir + "/batch_export" + ext, format, opts));
    return results;
}

void ShipExporter::OnExportComplete(std::function<void(const ExportResult&)> cb) {
    m_impl->onComplete = std::move(cb);
}

void ShipExporter::OnExportError(std::function<void(const std::string&)> cb) {
    m_impl->onError = std::move(cb);
}

} // namespace Builder
